# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class serviceAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.verify_payload = channel.unary_unary(
                '/ss.serviceA/verify_payload',
                request_serializer=services__pb2.payloadData.SerializeToString,
                response_deserializer=services__pb2.ok.FromString,
                _registered_method=True)


class serviceAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def verify_payload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serviceAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'verify_payload': grpc.unary_unary_rpc_method_handler(
                    servicer.verify_payload,
                    request_deserializer=services__pb2.payloadData.FromString,
                    response_serializer=services__pb2.ok.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ss.serviceA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ss.serviceA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class serviceA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def verify_payload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ss.serviceA/verify_payload',
            services__pb2.payloadData.SerializeToString,
            services__pb2.ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class serviceBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.verify_image = channel.unary_unary(
                '/ss.serviceB/verify_image',
                request_serializer=services__pb2.imageData.SerializeToString,
                response_deserializer=services__pb2.ok.FromString,
                _registered_method=True)


class serviceBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def verify_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serviceBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'verify_image': grpc.unary_unary_rpc_method_handler(
                    servicer.verify_image,
                    request_deserializer=services__pb2.imageData.FromString,
                    response_serializer=services__pb2.ok.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ss.serviceB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ss.serviceB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class serviceB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def verify_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ss.serviceB/verify_image',
            services__pb2.imageData.SerializeToString,
            services__pb2.ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class serviceCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.verify_validation = channel.unary_unary(
                '/ss.serviceC/verify_validation',
                request_serializer=services__pb2.validation.SerializeToString,
                response_deserializer=services__pb2.ok.FromString,
                _registered_method=True)


class serviceCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def verify_validation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serviceCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'verify_validation': grpc.unary_unary_rpc_method_handler(
                    servicer.verify_validation,
                    request_deserializer=services__pb2.validation.FromString,
                    response_serializer=services__pb2.ok.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ss.serviceC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ss.serviceC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class serviceC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def verify_validation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ss.serviceC/verify_validation',
            services__pb2.validation.SerializeToString,
            services__pb2.ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
