# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x02ss\"\x1e\n\x0bpayloadData\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x1e\n\timageData\x12\x11\n\timageData\x18\x01 \x01(\t\"\x1b\n\nvalidation\x12\r\n\x05valid\x18\x01 \x01(\x08\"\x10\n\x02ok\x12\n\n\x02ok\x18\x01 \x01(\t25\n\x08serviceA\x12)\n\x0everify_payload\x12\x0f.ss.payloadData\x1a\x06.ss.ok21\n\x08serviceB\x12%\n\x0cverify_image\x12\r.ss.imageData\x1a\x06.ss.ok27\n\x08serviceC\x12+\n\x11verify_validation\x12\x0e.ss.validation\x1a\x06.ss.okb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOADDATA']._serialized_start=22
  _globals['_PAYLOADDATA']._serialized_end=52
  _globals['_IMAGEDATA']._serialized_start=54
  _globals['_IMAGEDATA']._serialized_end=84
  _globals['_VALIDATION']._serialized_start=86
  _globals['_VALIDATION']._serialized_end=113
  _globals['_OK']._serialized_start=115
  _globals['_OK']._serialized_end=131
  _globals['_SERVICEA']._serialized_start=133
  _globals['_SERVICEA']._serialized_end=186
  _globals['_SERVICEB']._serialized_start=188
  _globals['_SERVICEB']._serialized_end=237
  _globals['_SERVICEC']._serialized_start=239
  _globals['_SERVICEC']._serialized_end=294
# @@protoc_insertion_point(module_scope)
